#!/bin/bash

inverted=1

while true
do
  i3-msg -t subscribe '[  "workspace",  "output",  "mode",  "window",  "barconfig_update",  "binding" ]' > /dev/null

  echo "event"
  sleep 0.1
  brightness=$(scrot /tmp/root.png ; convert /tmp/root.png -colorspace gray -format "%[fx:100*mean]" info: | sed -e 's/\..*//')
  #scrot /tmp/root.png
  #ls -l --full-time /tmp/root.png
  #convert /tmp/root.png -colorspace gray -format "%[fx:100*mean]\n" info:
  echo "brightness: $brightness"
  echo "inverted: $inverted"

  if ( ( [[ 0 -eq $(( inverted % 2)) ]] && [[ $brightness -le 20 ]] ) ||
	( [[ 1 -eq $(( inverted % 2)) ]] && [[ $brightness -ge 80 ]] ) )
	then
	  echo "Inverting"
	  xcalib -a -i
	  echo "Inverted"
	  inverted=$(( inverted + 1 ))
  fi
done
